inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'log/*'
    - 'public/*'
    - 'tmp/*'
    - 'vendor/*'
  TargetRubyVersion: 2.4

Documentation:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/**/*'

Metrics/MethodLength:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes
