inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'log/*'
    - 'public/*'
    - 'tmp/*'
    - 'vendor/*'
  TargetRubyVersion: 2.6

Documentation:
  Enabled: false

Layout/AlignHash:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 30

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: "[]"

StringLiterals:
  EnforcedStyle: double_quotes
