require: rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'log/*'
    - 'public/*'
    - 'tmp/*'
    - 'vendor/*'
  TargetRubyVersion: 2.6

Layout/HashAlignment:
  Enabled: false

Layout/LineLength:
  Max: 100

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 30

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: "[]"

Style/StringLiterals:
  EnforcedStyle: double_quotes
