AllCops:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'log/*'
    - 'public/*'
    - 'tmp/*'
    - 'vendor/*'
  TargetRubyVersion: 2.4

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'db/**/*'

Metrics/MethodLength:
  Max: 20

Style/AlignHash:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver

StringLiterals:
  EnforcedStyle: double_quotes
